/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shadowowy (https://sketchfab.com/shadowowy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-tv-7cef86bade2b447d841c333bcab9287c
Title: Old TV
*/

import React, { useEffect, useRef, useState } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function FloatingTVModel(props: any) {
    const { scene } = useGLTF('/old_tv.glb')
    const [hover, setHover] = useState(false);

    useEffect(() => {
       document.body.style.cursor = hover ? 'pointer' : 'auto'
    }, [hover])
    // Optionally scale and adjust as needed
    scene.scale.set(0.015, 0.015, 0.015)

    const position = [-2,-3,-20];
    
  return (
    <Float floatIntensity={0.1} speed={0.1} floatingRange={[1, 2]}>
        <ambientLight intensity={2} />
        <directionalLight intensity={hover ? 200 : 3} position={[10, 10, 5]} />
        <group>
          <primitive 
            object={scene} 
            position={position} 
            onPointerOver={() => setHover(true)}
            onPointerOut={() => setHover(false)}
            onClick={() => window.open("https://www.youtube.com/@ThisIsDafna")}
          />
        </group>
    </Float>
  )
}

useGLTF.preload('/old_tv.glb')

