/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shadowowy (https://sketchfab.com/shadowowy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-tv-7cef86bade2b447d841c333bcab9287c
Title: Old TV
*/

import React, { useEffect, useRef, useState } from 'react'
import { Float, useGLTF } from '@react-three/drei'

export default function RecordPlayer({ setShowVinyls, showVinyls }: { setShowVinyls: (set: boolean) => void, showVinyls: boolean },) {
    const { scene } = useGLTF('/recordplayer.glb')
    const [hover, setHover] = useState(false);

    
    useEffect(() => {
       document.body.style.cursor = hover ? 'pointer' : 'auto'
    }, [hover])
    // Optionally scale and adjust as needed
    scene.scale.set(0.06, 0.06, 0.06)

    const position = [0,0,-350];
    
  return (
    <>
        <ambientLight intensity={2} />
        <directionalLight intensity={5} position={[10, 10, 5]} />
        <group>
          <primitive 
            object={scene} 
            position={position} 
            rotation={[0,Math.PI/2,Math.PI/4]}
            onPointerOver={(e:any) => {
                e.stopPropagation()
                setHover(true)
              }}
              onPointerOut={(e:any) => {
                e.stopPropagation()
                setHover(false)
              }}
            onClick={(e:any) => {
                e.stopPropagation();
                setShowVinyls(!showVinyls)
            }}
          />
        </group>
    </>
  )
}

useGLTF.preload('/recordplayer.glb')

